### PR TITLE
Plone6 compatibility

### PR DESCRIPTION
**Pull request by rber474**
Fixes issue #2: remove includeDependecies

### CODE REVIEW

**Comment by terapyon** [comment]
This PR works well on Plone 6.0.9.

**Comment by erral** [comment]
@calvinhp @cdw9 can you merge and do a release? Or alternatively add permissions to user `collective` on PyPI to make releases?

**Comment by rber474** [comment]
Thanks @erral !

**Comment by erral** [comment]
@cdw9 has grant the `collective` user on PyPI the proper permissions to handle the releases. I have requested the release-team to do a release of this package.

**Comment by erral** [comment]
... and the 2.0 release is available on pypi.

Thanks @mauritsvanrees

**Pull request merged**
